### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by ianchen0119** [ianchen0119/Introduce-to-5GC#1]
- [x] PDU Session (on going....)
- [x] NGAP (on going....)
- [x] Registration with AMF re-allocation (on going....)
- [x] OpenAPI (on going....)
- [x] 5G NR RRC 相關
- [x] 5G NF 通用架構
- [ ] GTP-U
- [x] SCTP
- [ ] MPTCP
- [x] ULCL 介紹
